title: Atharva Tyagi
logo: /assets/img/pic.png
description: Look, we all go through hard times, that's why it's "live yours" and it's not "live mine."
show_downloads: false
theme: jekyll-theme-minimal
